services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - changedetection-data:/datastore
    restart: unless-stopped

  website-to-pdf:  
    build:
      context: ./website-se-leke-pdf-tak
    container_name: website-to-pdf
    ports:
      - "8000:8000"
    volumes:
      - ./website-se-leke-pdf-tak:/app
    restart: unless-stopped

volumes:
  changedetection-data:



